const sentences = [
  "Anton is officially the newest face of Saint Laurent.",
  "Anton is officially joining the Saint Laurent family.",
  "Saint Laurent has Anton as its newest brand ambassador.",
  "Anton Lee is stepping into his new Saint Laurent era.",
  "Anton is entering a new chapter with Saint Laurent.",
  "Anton Lee officially represents Saint Laurent in a whole new era.",
  "Saint Laurent has chosen Anton for a role made for his presence.",
  "Anton is the newest Saint Laurent ambassador, and it feels so right.",
  "Anton Lee joining Saint Laurent is a major fashion moment.",
  "Saint Laurent welcoming Anton feels like the start of something special.",
  "Anton is bringing his own identity to his new Saint Laurent role.",
  "Anton Lee is stepping into Saint Laurent as an official ambassador.",
  "Saint Laurent looks even more exciting with Anton as its newest ambassador.",
  "Anton is giving Saint Laurent a fresh new face.",
  "Anton Lee is the new Saint Laurent name everyone is talking about.",
  "Saint Laurent chose Anton for a reason, and the result is stunning.",
  "Anton officially becoming part of Saint Laurent is such a beautiful new chapter.",
  "Anton Lee is carrying the Saint Laurent name with effortless style.",
  "Saint Laurent has found a new ambassador with Anton's unmistakable presence.",
  "Anton is making his first Saint Laurent era feel instantly iconic.",
  "Anton Lee is officially a Saint Laurent ambassador, and the visuals speak for themselves.",
  "Saint Laurent looks right at home with Anton as its new ambassador.",
  "Anton is starting his Saint Laurent journey with undeniable style.",
  "Anton Lee brings a distinctive presence to his new Saint Laurent role.",
  "Saint Laurent welcoming Anton marks a new chapter worth remembering.",
  "Anton is officially part of the Saint Laurent family now.",
  "Anton Lee is stepping into Saint Laurent with a presence that feels completely his own.",
  "Saint Laurent has a fresh new energy with Anton as its ambassador.",
  "Anton is giving his new Saint Laurent title a seriously stylish beginning.",
  "Anton Lee becoming a Saint Laurent ambassador feels like a natural evolution of his fashion identity.",
  "Saint Laurent has Anton representing the house with effortless confidence.",
  "Anton is entering the Saint Laurent family looking every bit the part.",
  "Anton Lee is officially wearing the Saint Laurent name with his own signature style.",
  "Saint Laurent's newest ambassador Anton is already making an impression.",
  "Anton is starting his Saint Laurent ambassador era with a look to remember.",
  "Anton Lee is bringing a fresh perspective to his new Saint Laurent chapter.",
  "Saint Laurent's newest ambassador Anton is a perfect fit for this fashion moment.",
  "Anton is making his first official Saint Laurent era look effortless.",
  "Anton Lee officially joining Saint Laurent opens a striking new chapter in his fashion story.",
  "Saint Laurent's new ambassador Anton is already serving the house beautifully.",
  "Anton in Paris with Saint Laurent is a moment on its own.",
  "Saint Laurent has the perfect Paris Fashion Week muse in Anton.",
  "Anton brings Saint Laurent energy straight to Paris.",
  "Anton in Saint Laurent at Paris Fashion Week is a sight to remember.",
  "Anton wears Saint Laurent with the kind of presence made for Paris.",
  "This Saint Laurent look gives Anton that effortlessly chic PFW feeling.",
  "Anton in Saint Laurent is serving pure Paris Fashion Week energy.",
  "Anton makes every Saint Laurent outfit shine.",
  "Saint Laurent suits Anton like no other brand.",
  "Anton Lee looks born for Saint Laurent.",
  "Saint Laurent on Anton is dangerously stylish.",
  "Anton Lee in Saint Laurent is honestly breathtaking.",
  "Saint Laurent was made to be worn by Anton.",
  "Saint Laurent and Anton are a dream combination.",
  "The entire Saint Laurent look on Anton feels incredibly well balanced.",
  "Anton Lee is the face Saint Laurent deserves.",
  "Anton in Saint Laurent looks like a million-dollar campaign.",
  "Saint Laurent fits Anton's personality perfectly.",
  "Anton is absolutely glowing in Saint Laurent.",
  "Anton looks unreal from head to toe in Saint Laurent.",
  "Saint Laurent looks even more luxurious on Anton.",
  "Anton Lee and Saint Laurent belong together.",
  "This Saint Laurent look highlights Anton's naturally polished style.",
  "Anton in Saint Laurent is a complete visual experience.",
  "Anton Lee is giving timeless Saint Laurent elegance.",
  "Saint Laurent has never looked this good on Anton.",
  "Anton looks like he stepped out of a Saint Laurent editorial.",
  "Anton carries Saint Laurent with effortless confidence.",
  "Saint Laurent on Anton is everything I could ask for.",
  "Saint Laurent really knew what they were doing with Anton.",
  "Anton Lee makes Saint Laurent look unbelievably good.",
  "Anton looks insanely classy in Saint Laurent.",
  "Anton is the ultimate Saint Laurent boy.",
  "Saint Laurent on Anton is a whole new level of fashion.",
  "Saint Laurent and Anton were clearly meant to happen.",
  "Anton looks expensive, effortless, and very Saint Laurent.",
  "Saint Laurent on Anton is just unfair.",
  "Saint Laurent fits Anton beyond words.",
  "Anton makes Saint Laurent feel young, fresh, and cool.",
  "Anton in Saint Laurent is the definition of luxury.",
  "Anton wearing Saint Laurent is a blessing.",
  "Anton Lee and Saint Laurent are such a perfect match.",
  "Saint Laurent on Anton is simply beautiful.",
  "Anton represents the modern spirit of Saint Laurent perfectly.",
  "Saint Laurent suits Anton's aura so well.",
  "The styling of Anton's Saint Laurent outfit is exceptionally clean.",
  "Anton Lee is serving Saint Laurent excellence once again.",
  "Saint Laurent looks like it was made specifically for Anton.",
  "Anton Lee brings the perfect attitude to Saint Laurent.",
  "Anton in Saint Laurent is seriously too good.",
  "Anton is serving the coolest Saint Laurent look ever.",
  "Anton makes Saint Laurent look like pure art.",
  "Anton is effortlessly captivating in Saint Laurent.",
  "Anton looks like a walking Saint Laurent masterpiece.",
  "This Saint Laurent look is sleek, elegant, and perfect on Anton.",
  "Anton Lee is perfect for the Saint Laurent aesthetic.",
  "Anton in Saint Laurent is giving main character energy.",
  "Anton Lee and Saint Laurent are fashion chemistry at its finest.",
  "Anton in Saint Laurent is an unforgettable fashion moment.",
  "Anton Lee was made for this Saint Laurent era.",
  "Saint Laurent and Anton are a match we never knew we needed.",
  "Anton in Saint Laurent has exactly the kind of quiet luxury energy I love.",
  "Saint Laurent suits Anton perfectly every single time.",
  "Anton makes every Saint Laurent detail feel intentional.",
  "Anton is serving impeccable Saint Laurent style.",
  "Saint Laurent really brings out Anton's best style.",
  "Anton looks like a natural-born Saint Laurent model.",
  "Anton looks perfect in every Saint Laurent piece.",
  "Saint Laurent on Anton is an instant fashion classic.",
  "Saint Laurent on Anton is an entire mood.",
  "Saint Laurent and Anton create the kind of image you cannot look away from.",
  "Saint Laurent and Anton are simply made for each other.",
  "Saint Laurent was definitely made with Anton in mind.",
  "Saint Laurent on Anton is a lesson in effortless style.",
  "Anton looks like Saint Laurent royalty.",
  "Anton Lee belongs in a Saint Laurent campaign.",
  "Anton Lee in Saint Laurent is luxury personified.",
  "Anton looks ridiculously good in Saint Laurent.",
  "Saint Laurent and Anton are an iconic duo.",
  "Anton wears Saint Laurent like it was designed around his style.",
  "Saint Laurent has found its perfect match in Anton.",
  "Anton brings something uniquely his own to Saint Laurent.",
  "Anton looks like the face of Saint Laurent already.",
  "Anton Lee is the perfect person to wear Saint Laurent.",
  "Anton Lee is serving full Saint Laurent campaign energy.",
  "Anton in Saint Laurent is simply gorgeous.",
  "Anton gives this Saint Laurent outfit a sleek and modern finish.",
  "Anton Lee in Saint Laurent is a visual dream.",
  "Anton in Saint Laurent looks timeless yet completely current.",
  "Saint Laurent and Anton Lee just make sense.",
  "Saint Laurent and Anton Lee belong on every fashion moodboard.",
  "Anton makes Saint Laurent look effortlessly sophisticated.",
  "Saint Laurent and Anton Lee are giving fashion perfection.",
  "Anton looks absolutely flawless in this Saint Laurent look.",
  "Anton Lee and Saint Laurent are a match made in heaven.",
  "Anton looks stunning in Saint Laurent.",
  "Saint Laurent on Anton is pure fashion magic.",
  "Saint Laurent suits Anton like it was custom-made.",
  "Anton Lee makes every Saint Laurent moment special.",
  "Anton looks effortlessly iconic in Saint Laurent.",
  "Saint Laurent was made for someone like Anton.",
  "Anton looks like he belongs on a Saint Laurent billboard.",
  "Anton looks like he owns every Saint Laurent runway.",
  "Anton brings a quiet kind of power to Saint Laurent.",
  "Anton Lee was born to be a Saint Laurent muse.",
  "Saint Laurent looks so expensive on Anton.",
  "Anton Lee is serving high fashion in Saint Laurent.",
  "Anton in Saint Laurent is an absolute serve.",
  "Anton Lee brings effortless cool to Saint Laurent.",
  "Anton Lee was made to represent Saint Laurent.",
  "Anton looks incredibly elegant in Saint Laurent.",
  "Saint Laurent and Anton are pure luxury.",
  "Anton Lee is giving Saint Laurent superstar energy.",
  "Anton in Saint Laurent has an unmistakable fashion presence.",
  "Anton Lee makes Saint Laurent look even more powerful.",
  "Anton is the perfect Saint Laurent muse.",
  "Saint Laurent has never suited anyone like Anton.",
  "Anton in Saint Laurent is pure perfection.",
  "Anton is giving effortless luxury in Saint Laurent.",
  "Anton Lee and Saint Laurent are an unbeatable duo.",
  "Saint Laurent looks even cooler on Anton.",
  "There is a certain magic in Anton wearing Saint Laurent.",
  "Anton looks like the star of a Saint Laurent campaign.",
  "Anton Lee wearing Saint Laurent feels so right.",
  "Anton Lee in Saint Laurent is everything I needed today.",
  "The tailoring, texture, and attitude of Anton's Saint Laurent look are perfect together.",
  "Anton makes every Saint Laurent piece look amazing.",
  "Anton Lee in Saint Laurent is a fashion statement.",
  "This Saint Laurent look gives Anton a beautifully understated kind of luxury.",
  "Saint Laurent suits Anton's look so naturally.",
  "Saint Laurent fits Anton like a glove.",
  "Anton Lee makes every Saint Laurent look feel unforgettable.",
  "Anton Lee and Saint Laurent are simply everything.",
  "Anton looks like a Saint Laurent dream.",
  "Saint Laurent was clearly made for Anton.",
  "Saint Laurent and Anton look absolutely incredible together.",
  "Saint Laurent on Anton is a fashion dream come true.",
  "Saint Laurent and Anton are an effortless match.",
  "Anton Lee in Saint Laurent is a whole mood.",
  "Anton makes every Saint Laurent detail worth noticing.",
  "Saint Laurent fits Anton's style effortlessly.",
  "Anton is effortlessly owning this Saint Laurent moment.",
  "Saint Laurent on Anton is the fashion moment of the day.",
  "Saint Laurent and Anton are serving perfection again.",
  "Anton is giving iconic Saint Laurent energy.",
  "Anton looks unreal when he wears Saint Laurent.",
  "Saint Laurent and Anton are simply unmatched.",
  "Anton Lee is serving pure Saint Laurent style.",
  "Saint Laurent on Anton is perfection every time.",
  "Anton Lee makes Saint Laurent look effortlessly luxurious.",
  "Anton is serving serious Saint Laurent energy.",
  "Anton Lee looks made for the Saint Laurent runway.",
  "Anton looks like he walked straight out of Saint Laurent.",
  "Saint Laurent suits Anton's vibe perfectly.",
  "Saint Laurent looks perfect on Anton from every angle.",
  "Anton carries the essence of Saint Laurent with remarkable authenticity.",
  "Anton Lee gives Saint Laurent a whole new energy.",
  "Anton Lee and Saint Laurent are pure visual chemistry.",
  "Saint Laurent was made for Anton Lee's style.",
  "Saint Laurent on Anton is simply iconic.",
  "Saint Laurent on Anton is pure elegance.",
  "Saint Laurent + Anton is the combination we needed.",
  "Anton in Saint Laurent is a dream.",
  "Anton Lee is serving effortless Saint Laurent perfection.",
  "Saint Laurent looks perfect with Anton.",
  "Saint Laurent really found the perfect muse in Anton.",
  "Anton Lee is the perfect match for Saint Laurent.",
  "Saint Laurent and Anton together are simply unforgettable.",
  "Saint Laurent looks insanely good with Anton's style.",
  "Anton is absolutely killing it in Saint Laurent.",
  "Anton makes Saint Laurent look timeless.",
  "Anton Lee and Saint Laurent are simply meant to be.",
  "Saint Laurent fits Anton's aesthetic perfectly.",
  "Saint Laurent looks absolutely perfect on Anton.",
  "Anton looks like he was made for Saint Laurent.",
  "Saint Laurent and Anton look effortlessly perfect together.",
  "Anton Lee and Saint Laurent are a dream pairing.",
  "Anton and Saint Laurent were meant to meet.",
  "Anton looks like he belongs to the Saint Laurent universe.",
  "Anton Lee makes every Saint Laurent outfit look expensive.",
  "Anton makes every Saint Laurent moment iconic.",
  "Anton Lee is giving everything in Saint Laurent.",
  "Anton looks like a Saint Laurent campaign in human form.",
  "Anton gives every Saint Laurent look its own personality.",
  "Anton makes Saint Laurent look like it was made just for him.",
  "Anton looks like the perfect Saint Laurent boy.",
  "Anton Lee is made for the Saint Laurent world.",
  "Anton Lee brings Saint Laurent to life.",
  "Saint Laurent on Anton is everything a fashion moment should be.",
  "Anton is the perfect face for Saint Laurent.",
  "Anton looks effortlessly handsome in Saint Laurent.",
  "Saint Laurent and Anton are a perfect visual match.",
  "Saint Laurent really fits Anton's aura.",
  "Anton Lee looks unreal in Saint Laurent.",
  "Saint Laurent and Anton are the perfect fashion duo.",
  "Anton is effortlessly serving Saint Laurent.",
  "Saint Laurent on Anton is a whole aesthetic.",
  "Anton in Saint Laurent is a whole different level.",
  "Anton Lee is absolutely owning the Saint Laurent look.",
  "Anton Lee looks insanely expensive in Saint Laurent.",
  "Saint Laurent on Anton is a complete fashion serve.",
  "Anton Lee is serving Saint Laurent luxury.",
  "Anton in Saint Laurent is giving luxury and attitude.",
  "Anton Lee makes Saint Laurent feel effortlessly young and cool.",
  "Anton Lee makes Saint Laurent look even more desirable.",
  "Anton makes Saint Laurent look like luxury made human.",
  "Anton Lee is the face of Saint Laurent energy.",
  "Saint Laurent on Anton is unforgettable.",
  "Saint Laurent on Anton is simply stunning.",
  "Anton is the perfect new face for Saint Laurent.",
  "Saint Laurent and Anton feel like a natural match.",
  "Anton joining Saint Laurent is such an exciting new chapter.",
  "Saint Laurent has found an incredible new ambassador in Anton.",
  "Anton brings a fresh energy to Saint Laurent.",
  "Seeing Anton officially join Saint Laurent feels so right.",
  "Anton is a beautiful addition to the Saint Laurent family.",
  "Saint Laurent looks incredible with Anton as its new ambassador.",
  "Anton carries the Saint Laurent spirit with effortless confidence.",
  "This new chapter between Anton and Saint Laurent feels truly special.",
  "Anton is bringing his own identity to the Saint Laurent world.",
  "Saint Laurent and Anton share such a refined sense of style.",
  "Anton stepping into his Saint Laurent era feels absolutely right.",
  "Saint Laurent chose an incredible presence in Anton.",
  "Anton brings a distinctive charm to his new Saint Laurent role.",
  "The Saint Laurent chapter suits Anton beautifully.",
  "Anton as a Saint Laurent ambassador is a stunning combination.",
  "Saint Laurent feels perfectly aligned with Anton's personal style.",
  "Anton brings something uniquely his own to Saint Laurent.",
  "This Saint Laurent era is looking incredibly good on Anton.",
  "Anton is an exciting new presence in the Saint Laurent family.",
  "Saint Laurent found a remarkable ambassador in Anton.",
  "Anton represents a fresh and effortless side of Saint Laurent.",
  "The connection between Anton and Saint Laurent feels completely natural.",
  "Anton entering the Saint Laurent family is a moment worth celebrating.",
  "Saint Laurent and Anton are such a beautiful fashion pairing.",
  "Anton brings elegance, youth, and individuality to Saint Laurent.",
  "The Saint Laurent ambassador title looks perfect beside Anton's name.",
  "Anton is ready to make his mark in the Saint Laurent world.",
  "Saint Laurent has gained a truly distinctive new ambassador in Anton.",
  "Anton brings an unmistakable presence to his new Saint Laurent chapter.",
  "This new Saint Laurent era gives Anton so much room to shine.",
  "Anton and Saint Laurent together create such a strong visual identity.",
  "Anton stepping into Saint Laurent feels like the beginning of something special.",
  "Saint Laurent's newest ambassador Anton already feels right at home.",
  "Anton brings a modern elegance to the Saint Laurent family.",
  "The Saint Laurent title suits Anton effortlessly.",
  "Anton is an exciting new chapter for Saint Laurent.",
  "Saint Laurent and Anton make an effortlessly sophisticated pairing.",
  "Saint Laurent on Anton is a fashion masterpiece.",
];

let currentQuote = "";
let currentIndex = 0;

const quoteDisplay = document.getElementById("quoteDisplay");
const copyBtn = document.getElementById("copyBtn");

function generateQuote() {
  currentIndex = Math.floor(Math.random() * sentences.length);

  currentQuote = sentences[currentIndex];

  quoteDisplay.textContent = currentQuote;
  quoteDisplay.classList.remove("empty");

  copyBtn.textContent = "COPY";
}

function copyQuote() {
  if (!currentQuote) {
    alert("Please generate a sentence first!");
    return;
  }

  navigator.clipboard.writeText(currentQuote)
    .then(() => {
      copyBtn.textContent = "COPIED ✓";

      setTimeout(() => {
        copyBtn.textContent = "COPY";
      }, 1800);
    })
    .catch(() => {
      const textarea = document.createElement("textarea");

      textarea.value = currentQuote;

      document.body.appendChild(textarea);

      textarea.select();

      document.execCommand("copy");

      textarea.remove();

      copyBtn.textContent = "COPIED ✓";

      setTimeout(() => {
        copyBtn.textContent = "COPY";
      }, 1800);
    });
}